"
" SPDX-FileCopyrightText: (C) 2017-2024 Red Hat, Inc.
"
" SPDX-License-Identifier: GPL-2.0-or-later
"

let g:syntastic_clang_check_config_file = ".clang-check"
let g:syntastic_c_checkers = ['make', 'clang_check']

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
