actions:
  post-upstream-clone:
    - './autogen.sh'
    - './configure'
  create-archive:
    - 'make'
    - 'make dist'
    - 'bash -c "ls *.tar*"'
  get-current-version:
    - 'bash -c "./configure --version | head -n1 | cut -f3 -d\" \""'

jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-rawhide-aarch64
    - fedora-rawhide-ppc64le
    - fedora-rawhide-x86_64
    - fedora-latest-aarch64
    - fedora-latest-ppc64le
    - fedora-latest-x86_64
    - fedora-latest-stable-aarch64
    - fedora-latest-stable-ppc64le
    - fedora-latest-stable-x86_64
  trigger: pull_request

- job: copr_build
  trigger: commit
  owner: "@storage"
  project: sid-daily
  branch: main
  preserve_project: true

srpm_build_deps:
 - make
 - gcc
 - libtool
 - autoconf
 - autoconf-archive
 - automake
 - gperf
 - libtool
 - multilib-rpm-config
 - gcc
 - systemd-rpm-macros
 - systemd-devel
 - libudev-devel
 - libuuid-devel
 - libblkid-devel
 - device-mapper-multipath-devel

downstream_package_name: sid
specfile_path: rpm/sid.spec
